import type { Metadata } from 'next'
import type { ReactNode } from 'react'
import { Roboto } from 'next/font/google'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import cx from 'classnames'
import { RootProvider } from './provider'

// import '@workspace/ui-kit/src/style/tailwind.scss'
import './globals.scss'

const roboto = Roboto({ weight: ['400', '500'], subsets: ['cyrillic'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en">
    <body className={cx(roboto.className, 'antialiased text-text bg-bg-secondary')}>
    <AntdRegistry>
      <RootProvider>
        {children}
      </RootProvider>
    </AntdRegistry>
    </body>
    </html>
  )
}
