import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import { ReactNode } from 'react'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import { StyledComponentsRegistry } from '@/shared/lib/registers/styled-components-registry'
import { ThemeRegistry } from '@/shared/lib/registers/theme-registry'

const roboto = Roboto({ weight: ['400', '500'], subsets: ['cyrillic'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en">
    <body
      className={`${roboto.className} antialiased`}
    >
    <AntdRegistry>
      <StyledComponentsRegistry>
        <ThemeRegistry>
          {children}
        </ThemeRegistry>
      </StyledComponentsRegistry>
    </AntdRegistry>
    </body>
    </html>
  )
}
